<?xml version="1.0"?>

<robot xmlns:xacro="http://www.ros.org/wiki/xacro" 
    xmlns:sensor="http://playerstage.sourceforge.net/gazebo/xmlschema/#sensor"
    xmlns:controller="http://playerstage.sourceforge.net/gazebo/xmlschema/#controller"
    xmlns:interface="http://playerstage.sourceforge.net/gazebo/xmlschema/#interface"
    name="robot1_xacro">


  <property name="M_PI" value="3.1415926535897931"/>
  <property name="base_radius" value="0.117" />
  <property name="cube_2" value="1.414213562" />

  <xacro:macro name="default_inertial" params="mass">
    <inertial>
    <mass value="${mass}" />
    <inertia ixx="1.0" ixy="0.0" ixz="0.0"
        iyy="1.0" iyz="0.0"
        izz="1.0" />
    </inertial>
  </xacro:macro>

  <xacro:macro name="default_wheel">
    <visual>
      <geometry>
        <cylinder length=".02" radius="0.029"/> 
      </geometry>
      <!-- <origin rpy="0 1.5 0" xyz="0.1 0.1 0"/> -->
      <origin rpy="0 0 1.57075" xyz="0 0 0"/>
      <material name="black">
        <color rgba="0 0 0 1"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <cylinder length=".02" radius="0.029"/> 
      </geometry>
    </collision>
  </xacro:macro>

  <xacro:macro name="default_base_link">
    <visual>
      <geometry>
        <cylinder length=".01" radius="${base_radius}"/>
      </geometry>
      <origin rpy="0 0 1.57075" xyz="0 0 0"/> 
      <material name="white">
        <color rgba="1 1 1 1"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <cylinder length=".01" radius="${base_radius}"/>
      </geometry>
    </collision>
  </xacro:macro>

  <link name="base_link">
    <xacro:default_base_link />
    <xacro:default_inertial mass="10"/>
  </link>

  <link name="right_front_wheel">
    <xacro:default_wheel />
    <xacro:default_inertial mass="0.01"/>
  </link>

  <link name="right_back_wheel">
    <xacro:default_wheel />
    <xacro:default_inertial mass="0.01"/>
  </link>

  <link name="left_front_wheel">
    <xacro:default_wheel />
    <xacro:default_inertial mass="0.01"/>
  </link>

  <link name="left_back_wheel">
    <xacro:default_wheel />
    <xacro:default_inertial mass="0.01"/>
  </link>

  <joint name="right_front_wheel_joint" type="continuous">
    <parent link="base_link"/>
    <child link="right_front_wheel"/>
    <origin rpy="0 ${M_PI/2} 0" xyz="${base_radius/cube_2} ${base_radius/cube_2} -0.024"/> 
    <axis xyz="0 0 1" />
    <limit effort="100" velocity="100"/>
    <joint_properties damping="0.0" friction="0.0"/>
  </joint>

  <joint name="right_back_wheel_joint" type="continuous">
    <axis xyz="0 0 1" />
    <parent link="base_link"/>
    <child link="right_back_wheel"/>
    <origin rpy="0 ${M_PI/2} 0" xyz="${base_radius/cube_2} ${-base_radius/cube_2} -0.024"/> 
    <limit effort="100" velocity="100"/>
    <joint_properties damping="0.0" friction="0.0"/>
  </joint>

  <joint name="left_front_wheel_joint" type="continuous">
    <parent link="base_link"/>
    <axis xyz="0 0 1" />
    <child link="left_front_wheel"/>
    <origin rpy="0 ${M_PI/2} 0" xyz="${-base_radius/cube_2} ${base_radius/cube_2} -0.024"/>
    <limit effort="100" velocity="100"/>
    <joint_properties damping="0.0" friction="0.0"/>
  </joint>

  <joint name="left_back_wheel_joint" type="continuous">
    <parent link="base_link"/>
    <axis xyz="0 0 1" />
    <child link="left_back_wheel"/>
    <origin rpy="0 ${M_PI/2} 0" xyz="${-base_radius/cube_2} ${-base_radius/cube_2} -0.024"/>
    <limit effort="100" velocity="100"/>
    <joint_properties damping="0.0" friction="0.0"/>
  </joint>

  <!-- Drive controller -->
  <gazebo>
    <plugin name="skid_steer_drive_controller" filename="libgazebo_ros_skid_steer_drive.so">
      <updateRate>100.0</updateRate>
      <robotNamespace></robotNamespace>
      <leftFrontJoint>left_front_wheel_joint</leftFrontJoint>
      <rightFrontJoint>right_front_wheel_joint</rightFrontJoint>
      <leftRearJoint>left_back_wheel_joint</leftRearJoint>
      <rightRearJoint>right_back_wheel_joint</rightRearJoint>
      <wheelSeparation>4</wheelSeparation>
      <wheelDiameter>0.1</wheelDiameter>
      <commandTopic>cmd_vel</commandTopic>
      <odometryTopic>odom</odometryTopic>
      <robotBaseFrame>base_link</robotBaseFrame>
      <odometryFrame>odom</odometryFrame>
      <torque>1</torque>
      <topicName>cmd_vel</topicName>
      <broadcastTF>1</broadcastTF>
    </plugin>
  </gazebo>

  <!-- ros_control plugin -->
  <gazebo>
    <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
      <robotNamespace>/robot</robotNamespace>
    </plugin>
  </gazebo>


</robot>